version: '3.8'

services:

  postgres-link:
    image: postgres:16
    expose:
      - 5432
    env_file:
      - ./.env_docker
    volumes:
      - postgres-link-data:/var/lib/postgresql/data

  link-api:
    build: .
    command: sh -c "sleep 5 && alembic upgrade head && fastapi run src/main.py --port 8000"
    ports:
      - 8000:8000
    env_file:
      - ./.env_docker
    depends_on:
      - postgres-link

volumes:
  postgres-link-data: