"""01_initial-db

Revision ID: 3cb264b3fe84
Revises: 
Create Date: 2024-05-10 17:57:02.506514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cb264b3fe84'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('has_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_created_at'), 'link', ['created_at'], unique=False)
    op.create_table('link_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('params', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['link.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_access_created_at'), 'link_access', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_link_access_created_at'), table_name='link_access')
    op.drop_table('link_access')
    op.drop_index(op.f('ix_link_created_at'), table_name='link')
    op.drop_table('link')
    # ### end Alembic commands ###
